version: 0.2

phases:
  build:
    commands:
      - sam build

  post_build:
    commands:
      - sam package --output-template-file packaged.yaml --s3-bucket aws-chore-app

artifacts:
  type: zip
  files:
    - packaged.yaml
