version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ChoreApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qhogzyw0o9bj"
s3_prefix = "ChoreApp"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
