AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Chore_App

  Sample SAM Template for Chore_App
Parameters:
  PostgresDbname:
    Type: String
  PostgresHost:
    Type: String
  PostgresPass:
    Type: String
  PostgresPort:
    Type: String
  PostgresUser:
    Type: String
Metadata:
  AWS::ServerlessRepo::Application:
    Name: aws-chore-app
    Description: App to keep track of chores.
    Author: tharalso
    Labels: ['tests']
    HomePageUrl: https://github.com/tharalso/Chore_App
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/tharalso/Chore_App
   
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  GetAllUserChores:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      VpcConfig: 
        SecurityGroupIds: [ "sg-d2c055a0" ]
        SubnetIds: [ "subnet-0067985a" , "subnet-e6eb4980"]
      CodeUri: ./get-all-user-chores/
      Handler: getAllUserChores.lambdaHandler
      Events: 
        HelloWorld:
          Type: Api
          Properties:
            Path: /GetAllUserChores
            Method: get
      Environment:
        Variables:
          POSTGRES_DBNAME: !Ref PostgresDbname
          POSTGRES_HOST: !Ref PostgresHost
          POSTGRES_PASS: !Ref PostgresPass
          POSTGRES_PORT: !Ref PostgresPort
          POSTGRES_USER: !Ref PostgresUser
  RotateChores:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs10.x
      VpcConfig: 
        SecurityGroupIds: [ "sg-d2c055a0" ]
        SubnetIds: [ "subnet-0067985a" , "subnet-e6eb4980"]
      CodeUri: ./rotate-chores/
      Handler: rotateChores.lambdaHandler
      Events:
        UpdateChoresEvent:
          Type: Schedule
          Properties:
            Schedule: chron(0 0 * * MON *)
      Environment:
        Variables:
          POSTGRES_DBNAME: !Ref PostgresDbname
          POSTGRES_HOST: !Ref PostgresHost
          POSTGRES_PASS: !Ref PostgresPass
          POSTGRES_PORT: !Ref PostgresPort
          POSTGRES_USER: !Ref PostgresUser